name: video_player_skin
description: video_player_skin the skin
version: 2.2.8
homepage: ''

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fijkplayer: ^0.10.0
  wakelock: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
